EXPERIMENT_NAME = "mission_navigation_test"

WORLD_WIDTH = 1000
WORLD_HEIGHT = 700

NEIGHBOR_RADIUS = 100

OBSTACLE_LOOKAHEAD = 150

SEPARATION_STRENGTH = 50
MAX_STEERING_FORCE = 50
MAX_SPEED = 150


ZONE_ARRIVAL_RADIUS = 30

SEPARATION_WEIGHT = 1.5
ALIGNMENT_WEIGHT = 0.8
COHESION_WEIGHT = 0.6
OBSTACLE_AVOIDANCE_WEIGHT = 1.5
TARGET_SEEKING_WEIGHT = 1.0

SIMULATION_DURATION = 30.0