import { useState } from "react";

import flood1 from "../assets/demoperceptionimages/flood1.png";
import flood2 from "../assets/demoperceptionimages/flood2.png";
import landslide from "../assets/demoperceptionimages/landslide.png";
import buildingCollapse from "../assets/demoperceptionimages/buildingcollapse.png";
import earthquake from "../assets/demoperceptionimages/earthquake.png";


function Perception() {

  // DEMO PERCEPTION DATA
  // Later this can be replaced by the actual perception model output.

  const images = [
    {
      name: "Flood Detection",
      file: flood1,
      type: "Flood",
      drone: "DR-003",
      detections: 3,
      confidence: "94%",
      sensor: "RGB + Thermal"
    },

    {
      name: "Flood Search Area",
      file: flood2,
      type: "Flood",
      drone: "DR-002",
      detections: 2,
      confidence: "91%",
      sensor: "RGB"
    },

    {
      name: "Landslide Detection",
      file: landslide,
      type: "Landslide",
      drone: "DR-001",
      detections: 4,
      confidence: "88%",
      sensor: "RGB"
    },

    {
      name: "Building Collapse",
      file: buildingCollapse,
      type: "Building Collapse",
      drone: "DR-004",
      detections: 2,
      confidence: "89%",
      sensor: "RGB"
    },

    {
      name: "Earthquake Damage",
      file: earthquake,
      type: "Earthquake",
      drone: "DR-003",
      detections: 5,
      confidence: "86%",
      sensor: "RGB"
    }
  ];


  const [selectedImage, setSelectedImage] = useState(images[0]);


  return (
    <main className="dashboard">

      {/* =========================
          PAGE HEADER
      ========================== */}

      <section className="hero-section">

        <div>

          <p className="eyebrow">
            AI PERCEPTION
          </p>

          <h2>
            Disaster <span>Detection</span>
          </h2>

          <p className="hero-description">
            Monitor visual and thermal detections
            generated by the VayuNetra drone swarm.
          </p>

        </div>


        <div className="mission-status">

          <span className="status-dot"></span>

          PERCEPTION ONLINE

        </div>

      </section>


      {/* =========================
          MAIN DETECTION FEED
      ========================== */}

      <section
        className="map-panel"
        style={{ marginTop: "18px" }}
      >

        <div className="panel-header">

          <div>

            <p>
              PERCEPTION FEED
            </p>

            <h3>
              {selectedImage.name}
            </h3>

          </div>


          <span className="map-status">
            ● DEMO FEED
          </span>

        </div>


        <div
          style={{
            padding: "25px",
            display: "grid",
            gridTemplateColumns: "2fr 1fr",
            gap: "20px"
          }}
        >

          {/* IMAGE */}

          <div
            style={{
              borderRadius: "14px",
              overflow: "hidden",
              border:
                "1px solid rgba(255,255,255,0.08)",
              background: "#080b12",
              minHeight: "320px",
              display: "flex",
              alignItems: "center",
              justifyContent: "center"
            }}
          >

            <img
              src={selectedImage.file}
              alt={selectedImage.name}
              style={{
                width: "100%",
                height: "360px",
                objectFit: "cover",
                display: "block"
              }}
            />

          </div>


          {/* DETECTION INFORMATION */}

          <div className="dashboard-card">

            <div>

              <p>
                DETECTION INFORMATION
              </p>

              <h3>
                {selectedImage.type}
              </h3>

              <span>
                Current demo analysis result
              </span>


              <div
                style={{
                  marginTop: "20px",
                  display: "grid",
                  gap: "15px"
                }}
              >

                <div>
                  🚁 Drone:
                  <strong>
                    {" "}{selectedImage.drone}
                  </strong>
                </div>


                <div>
                  🎯 Confidence:
                  <strong>
                    {" "}{selectedImage.confidence}
                  </strong>
                </div>


                <div>
                  👁 Objects Detected:
                  <strong>
                    {" "}{selectedImage.detections}
                  </strong>
                </div>


                <div>
                  📡 Sensor:
                  <strong>
                    {" "}{selectedImage.sensor}
                  </strong>
                </div>

              </div>

            </div>

          </div>

        </div>

      </section>


      {/* =========================
          IMAGE SELECTOR
      ========================== */}

      <section
        className="map-panel"
        style={{ marginTop: "18px" }}
      >

        <div className="panel-header">

          <div>

            <p>
              MISSION IMAGERY
            </p>

            <h3>
              Detection Samples
            </h3>

          </div>

        </div>


        <div
          style={{
            padding: "20px",
            display: "grid",
            gridTemplateColumns:
              "repeat(5, 1fr)",
            gap: "12px"
          }}
        >

          {images.map((image) => (

            <button
              key={image.name}
              onClick={() => setSelectedImage(image)}
              style={{
                padding: "0",
                border:
                  selectedImage.name === image.name
                    ? "2px solid #8b5cf6"
                    : "1px solid rgba(255,255,255,0.08)",
                borderRadius: "12px",
                overflow: "hidden",
                background: "#080b12",
                cursor: "pointer",
                textAlign: "left"
              }}
            >

              <img
                src={image.file}
                alt={image.name}
                style={{
                  width: "100%",
                  height: "110px",
                  objectFit: "cover",
                  display: "block"
                }}
              />


              <div
                style={{
                  padding: "10px"
                }}
              >

                <div
                  style={{
                    color: "#ffffff",
                    fontSize: "11px",
                    fontWeight: "600"
                  }}
                >
                  {image.type}
                </div>


                <div
                  style={{
                    color: "#697386",
                    fontSize: "9px",
                    marginTop: "4px"
                  }}
                >
                  {image.drone}
                </div>

              </div>

            </button>

          ))}

        </div>

      </section>


      {/* =========================
          DETECTION SUMMARY
      ========================== */}

      <section
        className="map-panel"
        style={{ marginTop: "18px" }}
      >

        <div className="panel-header">

          <div>

            <p>
              AI ANALYSIS
            </p>

            <h3>
              Detection Results
            </h3>

          </div>

        </div>


        <div style={{ padding: "20px" }}>

          <div
            style={{
              display: "grid",
              gridTemplateColumns:
                "repeat(4, 1fr)",
              gap: "12px"
            }}
          >

            {/* SURVIVORS */}

            <div className="dashboard-card">

              <div>

                <p>
                  SURVIVORS
                </p>

                <h3>
                  3
                </h3>

                <span>
                  Detected persons
                </span>

              </div>

            </div>


            {/* FIRE */}

            <div className="dashboard-card">

              <div>

                <p>
                  FIRE
                </p>

                <h3>
                  1
                </h3>

                <span>
                  Fire detection
                </span>

              </div>

            </div>


            {/* DEBRIS */}

            <div className="dashboard-card">

              <div>

                <p>
                  DEBRIS
                </p>

                <h3>
                  4
                </h3>

                <span>
                  Obstacles detected
                </span>

              </div>

            </div>


            {/* CONFIDENCE */}

            <div className="dashboard-card">

              <div>

                <p>
                  CONFIDENCE
                </p>

                <h3>
                  {selectedImage.confidence}
                </h3>

                <span>
                  Current detection
                </span>

              </div>

            </div>

          </div>

        </div>

      </section>


      {/* =========================
          DETECTION LOG
      ========================== */}

      <section
        className="map-panel"
        style={{ marginTop: "18px" }}
      >

        <div className="panel-header">

          <div>

            <p>
              DETECTION LOG
            </p>

            <h3>
              Detected Objects
            </h3>

          </div>

        </div>


        <div
          style={{
            padding: "20px",
            overflowX: "auto"
          }}
        >

          <table
            style={{
              width: "100%",
              borderCollapse: "collapse",
              fontSize: "11px"
            }}
          >

            <thead>

              <tr
                style={{
                  textAlign: "left",
                  borderBottom:
                    "1px solid rgba(255,255,255,0.08)"
                }}
              >

                <th style={thStyle}>
                  DRONE
                </th>

                <th style={thStyle}>
                  OBJECT
                </th>

                <th style={thStyle}>
                  CONFIDENCE
                </th>

                <th style={thStyle}>
                  SENSOR
                </th>

                <th style={thStyle}>
                  DISASTER
                </th>

              </tr>

            </thead>


            <tbody>

              <tr>

                <td style={tdStyle}>
                  DR-003
                </td>

                <td style={tdStyle}>
                  Survivor
                </td>

                <td style={tdStyle}>
                  94%
                </td>

                <td style={tdStyle}>
                  Thermal
                </td>

                <td style={tdStyle}>
                  Flood
                </td>

              </tr>


              <tr>

                <td style={tdStyle}>
                  DR-003
                </td>

                <td style={tdStyle}>
                  Survivor
                </td>

                <td style={tdStyle}>
                  91%
                </td>

                <td style={tdStyle}>
                  RGB
                </td>

                <td style={tdStyle}>
                  Flood
                </td>

              </tr>


              <tr>

                <td style={tdStyle}>
                  DR-001
                </td>

                <td style={tdStyle}>
                  Debris
                </td>

                <td style={tdStyle}>
                  88%
                </td>

                <td style={tdStyle}>
                  RGB
                </td>

                <td style={tdStyle}>
                  Landslide
                </td>

              </tr>


              <tr>

                <td style={tdStyle}>
                  DR-004
                </td>

                <td style={tdStyle}>
                  Structural Damage
                </td>

                <td style={tdStyle}>
                  89%
                </td>

                <td style={tdStyle}>
                  RGB
                </td>

                <td style={tdStyle}>
                  Building Collapse
                </td>

              </tr>


              <tr>

                <td style={tdStyle}>
                  DR-003
                </td>

                <td style={tdStyle}>
                  Structural Damage
                </td>

                <td style={tdStyle}>
                  86%
                </td>

                <td style={tdStyle}>
                  RGB
                </td>

                <td style={tdStyle}>
                  Earthquake
                </td>

              </tr>

            </tbody>

          </table>

        </div>

      </section>


      {/* =========================
          INTEGRATION INFORMATION
      ========================== */}

      <section
        className="map-panel"
        style={{ marginTop: "18px" }}
      >

        <div
          style={{
            padding: "18px",
            color: "#697386",
            fontSize: "10px"
          }}
        >

          <strong>
            Integration fields:
          </strong>

          {" "}
          Image → Perception
          {" | "}
          Detection Class → YOLO / Thermal
          {" | "}
          Confidence → Perception
          {" | "}
          Location → Localisation
          {" | "}
          Drone ID → Swarm System

        </div>

      </section>

    </main>
  );
}


/* =========================
   TABLE HEADER STYLE
========================= */

const thStyle = {
  padding: "12px",
  color: "#858da5",
  fontSize: "9px",
  letterSpacing: "0.8px",
  fontWeight: "600"
};


/* =========================
   TABLE DATA STYLE
========================= */

const tdStyle = {
  padding: "12px",
  color: "#aeb3c7",
  borderBottom:
    "1px solid rgba(255,255,255,0.05)"
};


export default Perception;